-- Runtime paths are relative to the model's curated repository in Miguel's HF namespace.
-- Setup installs runtimes only. The server downloads a selected artifact on first load.
-- vLLM artifacts are deliberately disabled until each device-specific runtime passes the
-- same real-inference smoke checks. vLLM candidates can be produced only through
-- explicit, curated quantization schemes and remain disabled until runtime validation.
mica.settings {
  default_hf_repo = "miguelamendez/mica-server-catalog",
  llama_cpp_revision = "latest",
  audio_cpp_revision = "latest",
}

mica.model {
  id = "spark-x25-4b",
  capability = "text",
  description = "Spark-X2.5-4B text model; no native MTP/DFlash exists, and its 1.7B sibling remains disabled as an MLX classic drafter after losslessness tests failed.",
  tags = {"text-generation", "no-native-mtp", "classic-draft-disabled-mlx", "commercial-use", "apache-2.0"},
  source_repo = "XHToken/Spark-X2.5-4B",
  mlx_converter = "mlx_vlm.convert",
  mlx_repo = "miguelamendez/mica-spark-x25-4b",
  gguf_repo = "miguelamendez/mica-spark-x25-4b",
  gguf_context_tokens = 8192,
  gguf_parallel_slots = 4,
  priority = 10,
  required = true,
  mlx_q4_path = "q4",
  mlx_q4_repo_path = "mlx/q4",
  mlx_q4_quant_type = "mlx-affine-q4-g64",
  mlx_q4_size_bytes = 2327288292,
  mlx_q4_ram_gib = 3.2,
  mlx_q8_path = "q8",
  mlx_q8_repo_path = "mlx/q8",
  mlx_q8_quant_type = "mlx-affine-q8-g64",
  mlx_q8_size_bytes = 4383234908,
  mlx_q8_ram_gib = 5.4,
  gguf_supported = true,
  gguf_q4_path = "Spark-X2.5-4B-Q4_K_M.gguf",
  gguf_q4_repo_path = "gguf/Spark-X2.5-4B-Q4_K_M.gguf",
  gguf_q4_quant_type = "Q4_K_M",
  gguf_q4_size_bytes = 2600223552,
  gguf_q4_ram_gib = 4.8,
  gguf_q8_path = "Spark-X2.5-4B-Q8_0.gguf",
  gguf_q8_repo_path = "gguf/Spark-X2.5-4B-Q8_0.gguf",
  gguf_q8_quant_type = "Q8_0",
  gguf_q8_size_bytes = 4375020352,
  gguf_q8_ram_gib = 6.7,
  vllm_supported = false,
  vllm_reason = "Spark-X2.5 has not passed upstream vLLM or vLLM-Metal inference validation",
}

mica.model {
  id = "granite-speech-5",
  capability = "asr",
  description = "Granite Speech 5.0 470M TurboCTC automatic speech recognition model.",
  tags = {"automatic-speech-recognition", "audio", "commercial-use", "apache-2.0"},
  source_repo = "ibm-granite/granite-speech-5.0-470m-turboctc",
  mlx_converter = "mlx_audio.convert",
  mlx_quantization_profile = "granite-speech5-quality",
  gguf_family = "granite5asr",
  mlx_repo = "miguelamendez/mica-granite-speech-5",
  gguf_repo = "miguelamendez/mica-granite-speech-5",
  priority = 20,
  required = true,
  mlx_q4_path = "q4",
  mlx_q4_repo_path = "mlx/q4",
  mlx_q4_quant_type = "selective-mlx-affine-q4-g64",
  mlx_q4_size_bytes = 320409580,
  mlx_q4_ram_gib = 0.9,
  mlx_q8_path = "q8",
  mlx_q8_repo_path = "mlx/q8",
  mlx_q8_quant_type = "selective-mlx-affine-q8-g64",
  mlx_q8_size_bytes = 538513660,
  mlx_q8_ram_gib = 1.2,
  gguf_supported = true,
  gguf_q4_path = "granite-speech-5.0-470m-turboctc-q4_k.gguf",
  gguf_q4_repo_path = "gguf/granite-speech-5.0-470m-turboctc-q4_k.gguf",
  gguf_q4_quant_type = "Q4_K",
  gguf_q4_size_bytes = 272112352,
  gguf_q4_ram_gib = 0.9,
  gguf_q8_path = "granite-speech-5.0-470m-turboctc-q8_0.gguf",
  gguf_q8_repo_path = "gguf/granite-speech-5.0-470m-turboctc-q8_0.gguf",
  gguf_q8_quant_type = "Q8_0",
  gguf_q8_size_bytes = 504718560,
  gguf_q8_ram_gib = 1.4,
  vllm_supported = false,
  vllm_reason = "Granite TurboCTC has not passed a vLLM transcription worker smoke test",
}

mica.model {
  id = "audio8-tts-06b",
  capability = "tts",
  description = "Audio8 TTS Preview 0.6B local text-to-speech model.",
  tags = {"text-to-speech", "audio", "commercial-use", "apache-2.0"},
  source_repo = "Audio8/Audio8-TTS-Preview-0.6b",
  mlx_converter = "mlx_audio.convert",
  mlx_quantization_profile = "audio8-quality",
  gguf_family = "audio8_tts",
  mlx_repo = "miguelamendez/mica-audio8-tts-06b",
  gguf_repo = "miguelamendez/mica-audio8-tts-06b",
  priority = 30,
  required = false,
  mlx_q4_path = "q4",
  mlx_q4_repo_path = "mlx/q4",
  mlx_q4_quant_type = "selective-mlx-affine-q4-g64",
  mlx_q4_size_bytes = 1965243688,
  mlx_q4_ram_gib = 1.2,
  mlx_q8_path = "q8",
  mlx_q8_repo_path = "mlx/q8",
  mlx_q8_quant_type = "selective-mlx-affine-q8-g64",
  mlx_q8_size_bytes = 2173975882,
  mlx_q8_ram_gib = 1.8,
  gguf_supported = true,
  gguf_q4_path = "audio8-tts-preview-0.6b-q4_0.gguf",
  gguf_q4_repo_path = "gguf/audio8-tts-preview-0.6b-q4_0.gguf",
  gguf_q4_quant_type = "Q4_0",
  gguf_q4_size_bytes = 1092886528,
  gguf_q4_ram_gib = 1.6,
  gguf_q8_path = "audio8-tts-preview-0.6b-q8_0.gguf",
  gguf_q8_repo_path = "gguf/audio8-tts-preview-0.6b-q8_0.gguf",
  gguf_q8_quant_type = "Q8_0",
  gguf_q8_size_bytes = 1429544960,
  gguf_q8_ram_gib = 1.9,
  vllm_supported = false,
  vllm_reason = "Audio8 TTS is not a validated vLLM or vLLM-Omni speech worker",
}

mica.model {
  id = "minicpm-v46-thinking",
  capability = "vision",
  description = "MiniCPM-V 4.6 Thinking multimodal model for image and video understanding; no smaller compatible sibling or extractable MTP weights are published.",
  tags = {"image-text-to-text", "video-text-to-text", "thinking", "no-compatible-draft", "commercial-use", "apache-2.0"},
  source_repo = "openbmb/MiniCPM-V-4.6-Thinking",
  mlx_converter = "mlx_vlm.convert",
  mlx_repo = "miguelamendez/mica-minicpm-v46-thinking",
  gguf_repo = "miguelamendez/mica-minicpm-v46-thinking",
  gguf_context_tokens = 8192,
  gguf_parallel_slots = 1,
  priority = 40,
  required = false,
  mlx_q4_path = "q4",
  mlx_q4_repo_path = "mlx/q4",
  mlx_q4_quant_type = "selective-mlx-affine-q4-g64",
  mlx_q4_size_bytes = 2177913514,
  mlx_q4_ram_gib = 3.3,
  mlx_q8_path = "q8",
  mlx_q8_repo_path = "mlx/q8",
  mlx_q8_quant_type = "selective-mlx-affine-q8-g64",
  mlx_q8_size_bytes = 2332054242,
  mlx_q8_ram_gib = 3.5,
  gguf_supported = true,
  gguf_q4_path = "MiniCPM-V-4_6-Thinking-Q4_K_M.gguf",
  gguf_q4_repo_path = "gguf/MiniCPM-V-4_6-Thinking-Q4_K_M.gguf",
  gguf_q4_quant_type = "Q4_K_M",
  gguf_q4_size_bytes = 529101536,
  gguf_q4_projector = "mmproj-model-f16.gguf",
  gguf_q4_projector_repo_path = "gguf/mmproj-model-f16.gguf",
  gguf_q4_projector_size_bytes = 1108746976,
  gguf_q4_ram_gib = 2.2,
  gguf_q8_path = "MiniCPM-V-4_6-Thinking-Q8_0.gguf",
  gguf_q8_repo_path = "gguf/MiniCPM-V-4_6-Thinking-Q8_0.gguf",
  gguf_q8_quant_type = "Q8_0",
  gguf_q8_size_bytes = 811591648,
  gguf_q8_projector = "mmproj-model-f16.gguf",
  gguf_q8_projector_repo_path = "gguf/mmproj-model-f16.gguf",
  gguf_q8_projector_size_bytes = 1108746976,
  gguf_q8_ram_gib = 2.6,
  vllm_supported = false,
  vllm_reason = "Upstream vLLM supports MiniCPM-V 4.6, but vLLM-Metal does not list this vision family",
}

-- A validation-only control proves that the selected vLLM engine and Mica's
-- OpenAI proxy work even while the four production catalog architectures stay
-- disabled behind their model-specific compatibility gates.
mica.model {
  id = "vllm-qwen3-06b-control",
  capability = "text",
  catalog_visible = false,
  description = "Validation-only Qwen3 0.6B MLX Q4 control for vLLM-Metal acceptance; not a Mica production model.",
  tags = {"text-generation", "validation-control", "vllm-metal", "apache-2.0"},
  source_repo = "mlx-community/Qwen3-0.6B-4bit",
  mlx_supported = false,
  mlx_reason = "control is isolated to vLLM profiles",
  gguf_supported = false,
  gguf_reason = "control is isolated to vLLM profiles",
  vllm_repo = "mlx-community/Qwen3-0.6B-4bit",
  priority = 1,
  required = false,
  vllm_required = true,
  vllm_supported = true,
  vllm_q4_path = "q4",
  vllm_q4_format = "mlx",
  vllm_q4_quant_type = "mlx-affine-q4",
  vllm_q4_size_bytes = 351388974,
  vllm_q4_ram_gib = 1.5,
}

-- Bonsai 2 uses rotated ternary weights that require Prism's llama.cpp fork.
-- The exact upstream packing is retained as pq2_0; it is not relabeled Q4.
mica.model {
  id = "ternary-bonsai-2-27b",
  capability = "vision",
  description = "Ternary Bonsai 2 27B multimodal model using native PQ2_0 weights and the BF16 vision projector; requires the isolated Prism llama.cpp engine.",
  tags = {"image-text-to-text", "ternary", "pq2_0", "experimental", "commercial-use", "apache-2.0"},
  source_repo = "prism-ml/Ternary-Bonsai-2-27B-gguf",
  mlx_repo = "",
  gguf_repo = "prism-ml/Ternary-Bonsai-2-27B-gguf",
  gguf_revision = "6ed5e12bf84b7a63069882c91dd9e9218647d17b",
  gguf_context_tokens = 262144,
  gguf_parallel_slots = 1,
  priority = 50,
  required = false,
  mlx_supported = false,
  mlx_reason = "No certified MLX conversion is registered",
  gguf_supported = false,
  gguf_reason = "Bonsai is available only through its exact pq2_0 artifact variant",
  vllm_supported = false,
  vllm_reason = "Rotated PQ2_0 weights require the Prism llama.cpp activation transform",
  artifacts = {
    {
      backend = "gguf", variant = "pq2_0", supported = true,
      engine = "prism-llama-cpp", format = "gguf",
      quantization_type = "PQ2_0",
      path = "Ternary-Bonsai-2-27B-PQ2_0.gguf",
      repository_path = "Ternary-Bonsai-2-27B-PQ2_0.gguf",
      size_bytes = 7206168928,
      sha256 = "3907dc1658db1f78a9826bf8d5bcb8dc65db0d466388937af57f2294fae62ec1",
      projector = "Ternary-Bonsai-2-27B-mmproj-BF16.gguf",
      projector_repository_path = "Ternary-Bonsai-2-27B-mmproj-BF16.gguf",
      projector_size_bytes = 931145856,
      projector_sha256 = "e287342d92332fa3577ed1d42e921dac9370c08da58ba9337fa450f6cc76cfd7",
      reservation_gib = 12.0,
      size_source = "huggingface-pinned-revision",
    },
  },
}

mica.profile {
  name = "all",
  quantization = "q4",
  models = {"spark-x25-4b", "granite-speech-5", "audio8-tts-06b", "minicpm-v46-thinking"},
}

mica.profile {
  name = "core",
  quantization = "q4",
  models = {"spark-x25-4b", "granite-speech-5"},
}

mica.profile {
  name = "quality",
  quantization = "q8",
  models = {"spark-x25-4b", "granite-speech-5", "audio8-tts-06b", "minicpm-v46-thinking"},
}

-- Acceptance profiles are real selectable Mica profiles. The three context
-- tiers use the same public routes while binding one concrete backend and a
-- deterministic context/concurrency/KV policy. Modality-wide endpoint tests
-- continue to use `all`; these profiles isolate text context and batching.
mica.profile {
  name = "mlx-small",
  backend = "mlx",
  quantization = "q4",
  models = {"spark-x25-4b"},
  max_input_tokens = 512,
  max_output_tokens = 256,
  max_total_tokens = 1024,
  max_concurrent_requests = 4,
  kv_cache_precision = "q8",
}

mica.profile {
  name = "mlx-medium",
  backend = "mlx",
  quantization = "q4",
  models = {"spark-x25-4b"},
  max_input_tokens = 4096,
  max_output_tokens = 512,
  max_total_tokens = 4608,
  max_concurrent_requests = 2,
  kv_cache_precision = "q8",
}

mica.profile {
  name = "mlx-long",
  backend = "mlx",
  quantization = "q4",
  models = {"spark-x25-4b"},
  max_input_tokens = 16384,
  max_output_tokens = 1024,
  max_total_tokens = 17408,
  max_concurrent_requests = 1,
  kv_cache_precision = "q4",
}

mica.profile {
  name = "gguf-small",
  backend = "gguf",
  quantization = "q4",
  models = {"spark-x25-4b"},
  max_input_tokens = 512,
  max_output_tokens = 256,
  max_total_tokens = 1024,
  max_concurrent_requests = 4,
  kv_cache_precision = "q8",
}

mica.profile {
  name = "gguf-medium",
  backend = "gguf",
  quantization = "q4",
  models = {"spark-x25-4b"},
  max_input_tokens = 4096,
  max_output_tokens = 512,
  max_total_tokens = 4608,
  max_concurrent_requests = 2,
  kv_cache_precision = "q8",
}

mica.profile {
  name = "gguf-long",
  backend = "gguf",
  quantization = "q4",
  models = {"spark-x25-4b"},
  max_input_tokens = 16384,
  max_output_tokens = 1024,
  max_total_tokens = 17408,
  max_concurrent_requests = 1,
  kv_cache_precision = "q4",
}

mica.profile {
  name = "vllm-small",
  catalog_visible = false,
  backend = "vllm",
  quantization = "q4",
  models = {"vllm-qwen3-06b-control"},
  max_input_tokens = 512,
  max_output_tokens = 256,
  max_total_tokens = 1024,
  max_concurrent_requests = 4,
  kv_cache_precision = "auto",
}

mica.profile {
  name = "vllm-medium",
  catalog_visible = false,
  backend = "vllm",
  quantization = "q4",
  models = {"vllm-qwen3-06b-control"},
  max_input_tokens = 4096,
  max_output_tokens = 512,
  max_total_tokens = 4608,
  max_concurrent_requests = 2,
  kv_cache_precision = "auto",
}

mica.profile {
  name = "vllm-long",
  catalog_visible = false,
  backend = "vllm",
  quantization = "q4",
  models = {"vllm-qwen3-06b-control"},
  max_input_tokens = 16384,
  max_output_tokens = 1024,
  max_total_tokens = 17408,
  max_concurrent_requests = 1,
  kv_cache_precision = "auto",
}
